# Configuración para Nixpacks en Railway
# https://nixpacks.com/docs/configuration/file

[phases.install]
# Instala las extensiones de PHP necesarias.
# En este caso, la extensión para MongoDB.
nixPkgs = ["pkgs.php.extensions.mongodb"]