# Configuraci√≥n para Nixpacks en Railway
# https://nixpacks.com/docs/configuration/file

[providers]
php = "8.2"

[phases.setup]
nixPkgs = ["pkgs.php82Extensions.mongodb", "pkgs.php82Extensions.sodium"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"